// <auto-generated />
using System;
using ContratacaoService.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ContratacaoService.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ContratacaoDbContext))]
    partial class ContratacaoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ContratacaoService.Domain.Contratacoes.Contratacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DataContratacao")
                        .HasColumnType("timestamptz");

                    b.Property<string>("NumeroApolice")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<Guid>("PropostaId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorPremioPago")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("NumeroApolice")
                        .IsUnique();

                    b.HasIndex("PropostaId")
                        .IsUnique();

                    b.ToTable("Contratacoes", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
